# Generated by Django 2.0.6 on 2018-06-22 06:52

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=250, null=True, upload_to=Blog.models.upload_location, width_field=300),
        ),
    ]
